### ISSUE TITLE
How to get a notification when a new Nefit Easy version is available

### ISSUE THREAD

**Issue by mchangsp** [robertklep/homebridge-nefit-easy#14]
Hi Robert,
thank you for updating Nefit Easy whenever Nefit changes something.

A question: how can I receive an email whenever you release a new version/patch/fix?

regards
Marc

**Comment by robertklep** [comment]
Hi Marc!

I think the closest thing to what you're looking for is to press the "Watch" button at the top of the page. You'll get notified about any activity in this repository. However, this will apply to _any_ activity, not just new releases.

That said: I'm not actively working on this repository. You should assume that the only changes in the future will relate to changes that Nefit/Bosch makes which will break the functionality of this plugin, in which case the "notification" you get is that the plugin has stopped working 😅
