### ISSUE TITLE
can't install Nefit Easy on Raspberry pi 3

### ISSUE THREAD

**Issue by thomas192000** [robertklep/homebridge-nefit-easy#19]

**Comment by thomas192000** [comment]
it gives a error when installing

**Comment by robertklep** [comment]
Can you be a bit more elaborate? Just "it gives a error when installing" doesn't provide enough information for me to help you 😅

So please post the `npm-debug.log` file, or a screenshot that clearly shows the error and the log lines leading up to that error.

**Comment by thomas192000** [comment]
It's working today, but yesterday I'm not sorry for the trouble.

**Comment by robertklep** [comment]
No problem, glad to hear you got it working!
