### ISSUE TITLE
homebridge-config-ui-x and nefit easy plugin not working

### ISSUE THREAD

**Issue by bennievialle** [robertklep/homebridge-nefit-easy#25]
First thank you Robert for this plugin.. use it for years now... but i recently updated my PI from scratch and have installed homebridge-config-ui-x... is it possible that your plugin not works in here? I can't get it started... well i see the Nefit Easy device but can read or do anything with it... could you help me?

**Comment by robertklep** [comment]
To be honest, I've never used `homebridge-config-ui-x` (nor do I have a Homebridge setup so I can test it), so I have no idea why it's not working.

Have you checked to see if the Nefit device works through Homekit itself? If not, there might be something else going on; especially if you updated your PI from scratch, you may want to this [this](https://github.com/robertklep/nefit-easy-http-server#problems-on-recent-linux-distributions).

**Comment by bennievialle** [comment]
Thank you for the fast reply. I will try it in the normal mode, haven’t done that yet. The link you provided is to get to the server to check if it’s working right? But i can access the nefit easy by the original app. So it is online. But I will putt my findings here later....

**Comment by robertklep** [comment]
The link I provided points to an issue with recent Linux distributions that will prevent any Nefit implementation that I wrote (including the Homebridge plugin) from working from Linux. You need to change the OpenSSL configuration to fix that.

**Comment by bennievialle** [comment]
Ah ok sorry. Will look into that also. Let you know what will come from that. Thank you

**Comment by bennievialle** [comment]
Ok i tried to change the openssl file, but didn't help. Still 'no respons' from my Nefit Easy. I tried to start Homebridge without the config-ui-x, but in terminal i get the error "Error: listen EADDRINUSE: address already in use"... does this ring a bell?

**Comment by robertklep** [comment]
It means there's already something listening on a particular (TCP) port that Homebridge is using. But `homebridge-nefit-easy` doesn't listen on TCP ports itself, so my guess is that it might either be another plugin, or Homebridge itself (for the latter, you can change the port on which it listens in the Homebridge config file).

**Comment by bennievialle** [comment]
Yo are right... i did manage to change it and then Homebridge runs... but the Nefit Easy isn't working... it loads without errors, but if i want to set a temp or read the current temp in homekit, or google home they both give the reactie that the device isn't responding... Is there something else i could look into?

**Comment by robertklep** [comment]
Pass the correct credentials ;) XMPP authentication failures are caused by either the "serial number" or the "access code" not being correct.

**Comment by bennievialle** [comment]
I do have the correct credentials... Are the spaces needed?

**Comment by bennievialle** [comment]
now i see this... maybe you can understand this better then me?

**Comment by robertklep** [comment]
Config should be as per [the documentation](https://github.com/robertklep/homebridge-nefit-easy#configuration).

You could try installing the CLI utility, that will make testing a bit easier:
```
npm i -g nefit-easy-cli
```
(perhaps it will require using `sudo` in front of that command line)

To retrieve the current status of the Easy:
```
easy --serial=SERIAL --access-key=ACCESSKEY --password=PASSWORD status
```
Replace `SERIAL`, `ACCESSKEY` and `PASSWORD` with their respective values.

**Comment by bennievialle** [comment]
If i do that i get this as a response
`{"user mode":"manual","clock program":"auto","in house status":"ok","in house temp":21.6,"hot water active":true,"boiler indicator":"off","control":"room","temp override duration":0,"current switchpoint":36,"ps active":true,"powersave mode":true,"fp active":false,"fireplace mode":false,"temp override":false,"holiday mode":false,"boiler block":null,"boiler lock":null,"boiler maintenance":null,"temp setpoint":21.5,"temp override temp setpoint":19,"temp manual setpoint":21.5,"hed enabled":null,"hed device at home":null,"outdoor temp":6,"outdoor source type":"virtual"}`

this is ok right?

**Comment by robertklep** [comment]
Yeah, that's okay. No idea why it's failing for Homebridge. Can you post the Nefit-part of the Homebridge config here? (make sure to remove sensitive information)

**Comment by bennievialle** [comment]
i don't know what this does but it is working now... so thank you but a bit sad that i don't know what the solution was... but hey it is working and thanks again!

**Comment by robertklep** [comment]
Cool! Have fun 😁
