### ISSUE TITLE
spaties in config

### ISSUE THREAD

**Issue by tijsziere** [robertklep/homebridge-nefit-easy#26]
Hi Robert,

Ik krijg het helaas niet aan de praat, moeten het serialnumber en accesskey ingevuld worden met of zonder spatie?

Het is een nefit easy en ik heb de serial en accesskey uit de nefit easy app.

**Comment by rcuijpers** [comment]
Hi @tijsziere! Ik heb even in mijn config file gekeken en alles is zonder spaties of streepjes. :)

**Comment by tijsziere** [comment]
Bedankt voor het snelle antwoord! 

Op een of andere manier kan ik de status wel uitlezen met "easy --serial=XX --access-key=XX --password=XX status" maar geeft homebridge een "XMPP authentication failure". Enig idee waar dat aan zou kunnen liggen?

**Comment by rcuijpers** [comment]
Ja heb ik! Moet ff autorijden reageer zo

**Comment by robertklep** [comment]
bij "XMPP authentication failure" zijn serienummer en/of access key niet goed (wachtwoord wordt daar niet voor gebruikt). Serienummer van mij is een 9-cijferig nummer, access key bestaat uit 16 cijfers/letters (zowel hoofdletters als kleine letters).

**Comment by tijsziere** [comment]
Top, nu werkt het. Had inderdaad een tikfoutje in de Homebridge configuration!
Bedankt beiden!

**Comment by robertklep** [comment]
Mooi dat het werkt!
