### ISSUE TITLE
Dependencies fail

### ISSUE THREAD

**Issue by felix63** [robertklep/homebridge-nefit-easy#30]
Hi,

When installing a lot of dependencies fail. Is it time to update?

**Comment by robertklep** [comment]
I see exactly one deprecation warning when I install it, but no failures whatsoever. Which ones are failing? Or even better, what's the output of `npm i homebridge-nefit-easy -g`?

**Comment by felix63** [comment]
npm
28-6-2020 11:27:07  WARN deprecated node-xmpp-client@3.2.0: this package is deprecated please use https://www.npmjs.com/package/@xmpp/client
28-6-2020 11:27:08 npm
28-6-2020 11:27:08  WARN deprecated node-xmpp-core@5.0.9: this package is deprecated please use https://github.com/xmppjs/xmpp.js
28-6-2020 11:27:08 npm
28-6-2020 11:27:08  WARN deprecated node-xmpp-tls-connect@1.0.1: this package is deprecated please use https://github.com/xmppjs/xmpp.js
28-6-2020 11:27:16 + homebridge-nefit-easy@2.2.0
added 25 packages from 24 contributors in 16.068s
28-6-2020 11:27:17 
37 packages are looking for funding
  run `npm fund` for details
28-6-2020 11:27:17 Plugin "homebridge-nefit-easy" installed.

**Comment by robertklep** [comment]
Notice the _"Plugin "homebridge-nefit-easy" installed."_

Warnings are just that: warnings. I'm aware that `node-xmpp-client` is deprecated, but I've had many issues with its replacement in the past so reverted back to it. It's working fine.

**Comment by felix63** [comment]
Okay. Cool. Thanks for the response.
