### ISSUE TITLE
XMPP Authentication failure

### ISSUE THREAD

**Issue by FredBoekwijt** [robertklep/homebridge-nefit-easy#31]
Hi,

I appreciate you creating this plug in.

I am new to this but i have tried to install and use this however i get:
XMPP Authentication failure

I have install homebridge on my windows 10 pc using instructions from:
https://github.com/homebridge/homebridge/wiki/Install-Homebridge-on-Windows-10

I have this working correctly.
I have downloaded and installed the Homebridge Nefit Easy v2.2.0 plug in

I have added the accessory as per instructions on:
https://www.npmjs.com/package/homebridge-nefit-easy

I have added the homebridge to home app on my iPhone running iOS 14.0
I got the message to add the plug in.
I can see the name i gave to the plug in in the home hub also when i change the name it changes in the home app (so the connection is present)

However as soon as i open the home app it shows not responding and in the homebridge i see the message:
XMPP Authentication failure

I have checked the : serial Number accessKey and pasword and they are correct. 
"serialNumber" : "****",
"accessKey"    : "*****",
"password"     : "*****"

I am new to this but tried to locate other resources to try and assist me but at the moment i am stumped.
Would you be able to offer advise?

**Comment by robertklep** [comment]
To authenticate the XMPP connection, the serial number and access key are used. The serial number contains only digits (0-9), the access key alphanumericals (0-9 and a-zA-Z). The access key is case-sensitive, so "a" is not the same as "A".

An easier way of testing the connection is using the [`nefit-easy-cli`](https://github.com/robertklep/nefit-easy-cli) package. It uses the same core code as the Homebridge plugin, but you don't have to restart Homebridge for every change of the configuration.

**Comment by FredBoekwijt** [comment]
Thank you for you quick comment.

Now that i am sure it had to do something with the seiral number and access key i was able to resolve it :)
Seems you don't use spaces eventough the manual shows them having spaces.

Thank you very much
