### ISSUE TITLE
Plug-in not working after upgrading to version 1.3.0 of homebridge

### ISSUE THREAD

**Issue by martijnverheij** [robertklep/homebridge-nefit-easy#33]
I have recently upgraded my homebridge to version 1.3.0, after the upgrade i find out that the nefit easy plugin give me some errors.
I have tried to downgrade my homebridge version to an earlier version but the issue remains.

The error logs reports me “This plugin slows down homebridge. The read handler for the characteristic ‘*’ didn’t respond at all! Please check that you properly call the callback! See https://git.io/JtMGR for more info.
The ‘*’ is because of different characteristics.
![BD97D55C-2825-4698-AD70-AF6EDEF20D79](https://user-images.githubusercontent.com/46934436/108624019-74bae100-7442-11eb-8a34-57a89040338c.jpeg)

**Comment by robertklep** [comment]
The handlers for those characteristics return when the value is returned by the Easy. If that takes too long for whatever reason, I guess Homebridge will now post a warning. Not much I can do about it, though.

**Comment by martijnverheij** [comment]
Thanks for your quick reply. But my thermostat is not responding and i can’t control it :-(

**Comment by robertklep** [comment]
Does the official Nefit app still work okay? I don't have an Easy anymore so cannot check if there might be backend issues, for example.

**Comment by martijnverheij** [comment]
Yes, the official app is working normally. Can i do some checks?

**Comment by robertklep** [comment]
You can try and install the [CLI tool](https://github.com/robertklep/nefit-easy-cli) and run it from the same hardware that Homebridge is running from to see if it can contact your Easy.

**Comment by martijnverheij** [comment]
I found the issue... but a couple of months ago i have changed my firewall rules. Everything works fine But afther the upgrade the system will check of the firewall ports 1522 and 1523 are openend. I have reopend these ports and the issue is solved.

**Comment by robertklep** [comment]
Great, thanks for letting me know!
