### ISSUE TITLE
XMPP Error Code on New Homebridge Instance with Worcester Wave (Nefit Easy UK)

### ISSUE THREAD

**Issue by TurquoiseTNT** [robertklep/homebridge-nefit-easy#39]
I have started a new Homebridge Instance Error on My Raspberry Pi 4. I am Using The Official Homebridge Image from the Raspberry Pi Imager and when I re-enabled my Nefit Easy Plugin, It keeps giving me "XMPP Authentication Error" In my Homebridge Console.
In My Config, All my 3 Codes are Laid out like this:
            "accessory": "NefitEasy",
            "name": "Wave Heating",
            "options": {
                "serialNumber": "NEFIT_********",
                "accessKey": "NEFIT_*******************",
                "password": "NEFIT_*********"
            }
            
All My Codes are Copy-Pasted from my Worcester Wave app. (The App DOES work, before you ask)

**Comment by robertklep** [comment]
What are those `NEFIT_` prefixes you're using? They shouldn't be there.

**Comment by TurquoiseTNT** [comment]
I was doing it without the NEFIT_ but got another XMPP Auth Error and the
instructions on NMP made it look like that I then needed The NEFIT_<code>
Prefix.

**Comment by robertklep** [comment]
Sorry for the confusion, but you don't need the `NEFIT_` prefix.

XMPP authentication relies on the serial number (which should consist of only digits) and the access key (digits and characters, _case sensitive_). The password is only used for encryption/decryption, so only used when an XMPP connection has already been established.

**Comment by TurquoiseTNT** [comment]
Thanks! Btw, Is there any other tips for getting this plugin working with
Worcester Wave? (Was working on old install)

**Comment by robertklep** [comment]
I never tested the code against a Worcester Wave, I was only told it worked.

For a bit more easy debugging, you can install [`bosch-xmpp`](https://github.com/robertklep/bosch-xmpp) and use its command line tool to test and see if you can connect. It's a bit easier than a change-config-and-restart cycle with Homebridge.

**Comment by TurquoiseTNT** [comment]
That is Pretty Much the same for Worcester Wave (as in the way you get the codes)
