### ISSUE TITLE
Problem with json.config

### ISSUE THREAD

**Issue by wolter25** [robertklep/homebridge-nefit-easy#6]
Hi, I have a problem with the config.json file. I get an error that the file is incorrect when starting homebridge. I'm totally new to json programming. What am I doing wrong? Thanks in advance for your help!

![image](https://user-images.githubusercontent.com/33638406/32747614-9c689d2e-c8b9-11e7-94cf-9614967e0ea5.png)

**Comment by robertklep** [comment]
Looks like there's a missing `}` in the Nefit Easy configuration (after the `password` field).

**Comment by wolter25** [comment]
This was the problem indeed, thanks for your support!

**Comment by robertklep** [comment]
Have fun!
