### ISSUE TITLE
Meaning of the Modes

### ISSUE THREAD

**Issue by daaf84** [robertklep/homebridge-nefit-easy#8]
There are 4 modes: Off, Heating, cooling and automatic.
What will they do? Do they affect the program in the thermostat? Of are they all just manual overrides?

E.g.: My standard Program is 23.00 set to 15°C.
If i use homekit to set it to 17°C, will it stay there until the next program setting or what?
It's not documented for what I can see.

**Comment by robertklep** [comment]
There are only two modes relevant in combination with the Nefit Easy, _Off_ (when the central heating is not heating, "de verwarming staat uit") and _Heating_ (when the central heating is active, "de verwarming staat aan").

It's a read-only value, it can't be changed through HomeKit.

> E.g.: My standard Program is 23.00 set to 15°C.
> If i use homekit to set it to 17°C, will it stay there until the next program setting or what?
> It's not documented for what I can see.

This isn't really related to the modes, but it does what you say it does: it's a manual override of the currently set temperature.

So like you say, if the program is set to 15°C but you use HomeKit to set the temperature to 17°C, it will remain on 17°C until the next program switchpoint.

This is also how setting the temperature works on the Nefit Easy itself: the value you enter on the device overrides the program temperature until the next switchpoint.

**Comment by daaf84** [comment]
So, these buttons will not do anything. 
I've tested the 'automatic' button as well, but it won't switch back to automatic mode, when it was on manual before. (hand and clock symbol on the thermostat itself stays on manual) 

![image](https://user-images.githubusercontent.com/12270887/35908939-63ec3394-0bf2-11e8-8587-ba6abb8f1dd7.png)

**Comment by robertklep** [comment]
> So, these buttons will not do anything.

Correct, it will only show the current state but you can't change it. I don't think there's a way to declare a particular characteristic as "read-only" in HomeKit, so it's showing as if you can change the value, but you can't.

**Comment by daaf84** [comment]
Ok Thanks!
