### ISSUE TITLE
Nefit Easy problem

### ISSUE THREAD

**Issue by noppie** [robertklep/homebridge-nefit-easy#9]
Since 2 days my Homebridge won't get the temperature of my Nefit Easy anymore.  
May 30 20:34:00 raspberrypi homebridge[315]: [5/30/2018, 8:34:00 PM] [thermostaat] Getting current temperature...
May 30 20:34:00 raspberrypi homebridge[315]: [5/30/2018, 8:34:00 PM] [thermostaat] Getting target temperature...
May 30 20:34:00 raspberrypi homebridge[315]: undefined
May 30 20:34:00 raspberrypi homebridge[315]: undefined
May 30 20:34:00 raspberrypi homebridge[315]: undefined
May 30 20:34:02 raspberrypi homebridge[315]: [5/30/2018, 8:34:02 PM] [thermostaat] Getting target temperature...
May 30 20:34:02 raspberrypi homebridge[315]: [5/30/2018, 8:34:02 PM] [thermostaat] Getting current state..
May 30 20:34:02 raspberrypi homebridge[315]: [5/30/2018, 8:34:02 PM] [thermostaat] Getting current temperature...
May 30 20:34:02 raspberrypi homebridge[315]: undefined
May 30 20:34:02 raspberrypi homebridge[315]: undefined

Any idea how to solve this?

**Comment by robertklep** [comment]
I'll push an update shortly. Yesterday, Bosch changed their backend which stopped the underlying library from being able to connect to it.

However, it does mean that you need at least Node v6 in order to be able to keep running it.

**Comment by noppie** [comment]
Great!  It works again.  Thank you very much

**Comment by robertklep** [comment]
Thanks for testing!

**Comment by gladiatormax** [comment]
Thanks for the quick update !!!
